//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetXML", Namespace="http://schemas.datacontract.org/2004/07/Zuliaworks.Netzuela.Paris.ServidorValeria" +
        "")]
    [System.SerializableAttribute()]
    public partial class DataSetXML : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsquemaXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsquemaXML {
            get {
                return this.EsquemaXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.EsquemaXMLField, value) != true)) {
                    this.EsquemaXMLField = value;
                    this.RaisePropertyChanged("EsquemaXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XML {
            get {
                return this.XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLField, value) != true)) {
                    this.XMLField = value;
                    this.RaisePropertyChanged("XML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorValeria.IValeria")]
    public interface IValeria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValeria/RecibirTablas", ReplyAction="http://tempuri.org/IValeria/RecibirTablasResponse")]
        System.Data.DataSet RecibirTablas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValeria/EnviarTablas", ReplyAction="http://tempuri.org/IValeria/EnviarTablasResponse")]
        void EnviarTablas(Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria.DataSetXML TablaXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValeriaChannel : Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria.IValeria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValeriaClient : System.ServiceModel.ClientBase<Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria.IValeria>, Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria.IValeria {
        
        public ValeriaClient() {
        }
        
        public ValeriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValeriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValeriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValeriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RecibirTablas() {
            return base.Channel.RecibirTablas();
        }
        
        public void EnviarTablas(Zuliaworks.Netzuela.Valeria.LogicaPresentacion.ServidorValeria.DataSetXML TablaXML) {
            base.Channel.EnviarTablas(TablaXML);
        }
    }
}
